premiere livraison (#1)
PaylinePaymentMethod/payment-method-amazonpayv2 pull request #1
Opened 2020-11-25 16:53 UTC by JanFLORENT

![image](https://user-images.githubusercontent.com/41673610/100258154-02238d80-2f47-11eb-90a0-93ec2edfc477.png)

Les codeSmells viennent des Enum qui ne sont pas en MAJUSCULE

2020-12-01 10:05 UTC, monext-ofrancome commented
Je comprends pas le pb pour les code smells
Tu peux pas faire 
```
Enum {
ONE ("one"),
TWO("two")
}
```

et coller aux normes ?

2020-12-02 10:32 UTC, pesublet requested changes

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/bean/AmazonBean.java
> +public class AmazonBean {
alors tu peux optimiser un peu lombok ici avec :
@Getter
@SuperBuilder
@AllArgsConstructor

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/bean/CheckoutSession.java
> +public class CheckoutSession extends AmazonBean {
et optimiser du coup ici la classe :

```
@Value
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
public class CheckoutSession extends AmazonBean {
    String checkoutSessionId;
    ChargePermissionType chargePermissionType;
    RecurringMetaData recurringMetaData;
    WebCheckoutDetails webCheckoutDetails;
    String productType;
    PaymentDetails paymentDetails;
    MerchantMetadata merchantMetadata;
    String platformId;
    ProviderMetadata providerMetadata;
    Buyer buyer;
    Address shippingAddress;
    Address billingAddress;
    List<PaymentPreference> paymentPreferences;
    StatusDetails statusDetails;
    List<Constraint> constraints;
    Date expirationTimestamp;
    String chargePermissionId;
    String chargeId;
    String storeId;
    DeliverySpecifications deliverySpecifications;
}
```

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/bean/ErrorResponse.java
> +public class ErrorResponse {
tu peux simplifier en 
```
@Value
public class ErrorResponse {
    String reasonCode;
    String message;
}
```

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/bean/Refund.java
> +public class Refund extends AmazonBean {
tu peux simplifier en
```
@Value
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
public class Refund extends AmazonBean {
    String refundId;
    String chargeId;
    Price refundAmount;
    String softDescriptor;
    StatusDetails statusDetails;
}
```

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/bean/Script.java
> +public class Script {
```
@Builder
@Value
public class Script {

    @NonNull
    String merchantId;
    @NonNull
    String ledgerCurrency;
    boolean sandbox;
    String checkoutLanguage;
    ProductType productType;    // default is PayAndShip
    @NonNull
    Placement placement;
    ButtonColor buttonColor;    // default is Gold
    @NonNull
    CreateCheckoutSessionConfig createCheckoutSessionConfig;

}
```

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/bean/configuration/RequestConfiguration.java
> +public class RequestConfiguration {
@Value et supprimer les getters manuels et les champs en private

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/bean/configuration/RequestConfiguration.java
> +    public static RequestConfiguration build(CaptureRequest request) {
Pas de build dans un bean ! leur place est dans un service :)

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/bean/nested/Address.java
> +public class Address {
De la même manière tu peux optimiser tous les beans de ce package avec des @Value de partout

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/exception/PluginException.java
> +    public static String runtimeErrorCode(RuntimeException e) {
plutot dans un service

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/service/LogoPaymentFormConfigurationService.java
> +    private static final Logger LOGGER = LogManager.getLogger(LogoPaymentFormConfigurationService.class);
Tu peux utiliser le @Log de lombok

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/service/impl/ConfigurationServiceImpl.java
> +public class ConfigurationServiceImpl implements ConfigurationService {
@Log

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/service/impl/PaymentFormConfigurationServiceImpl.java
> +public class PaymentFormConfigurationServiceImpl extends LogoPaymentFormConfigurationService {
@Log, je te laisse regarder quand il faut l'ajouter à d'autres endroits :)

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/utils/PluginUtils.java
> +public class PluginUtils {
tu peux utiliser @UtilityClass de lombok

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/utils/amazon/ErrorConverter.java
> +public class ErrorConverter {
@UtilityClass

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/utils/amazon/ReasonCodeConverter.java
> +public class ReasonCodeConverter {
@UtilityClass

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/utils/constant/ContractConfigurationKeys.java
> +public class ContractConfigurationKeys {
@UtilityClass

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/utils/constant/PartnerConfigurationKeys.java
> +public class PartnerConfigurationKeys {
@UtilityClass

2020-12-02 10:32 UTC, pesublet commented on src/main/java/com/payline/payment/amazonv2/utils/constant/RequestContextKeys.java
> +public class RequestContextKeys {
@UtilityClass

2020-12-02 10:32 UTC, pesublet commented on src/test/java/com/payline/payment/amazonv2/MockUtils.java
> +public class MockUtils {
@UtilityClass

2020-12-03 08:59 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/bean/configuration/RequestConfiguration.java
> +public class RequestConfiguration {
Fait

2020-12-03 08:59 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/bean/Script.java
> +public class Script {
Fait

2020-12-03 08:59 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/bean/Refund.java
> +public class Refund extends AmazonBean {
Fait

2020-12-03 09:00 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/bean/ErrorResponse.java
> +public class ErrorResponse {
Fait

2020-12-03 09:00 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/bean/CheckoutSession.java
> +public class CheckoutSession extends AmazonBean {
Fait

2020-12-03 09:00 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/bean/AmazonBean.java
> +public class AmazonBean {
Fait

2020-12-03 09:02 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/bean/nested/Address.java
> +public class Address {
Fait

2020-12-03 09:54 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/utils/amazon/ReasonCodeConverter.java
> +public class ReasonCodeConverter {
Fait

2020-12-03 09:55 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/utils/constant/ContractConfigurationKeys.java
> +public class ContractConfigurationKeys {
Fait

2020-12-03 09:55 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/utils/constant/PartnerConfigurationKeys.java
> +public class PartnerConfigurationKeys {
Fait

2020-12-03 09:55 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/utils/constant/RequestContextKeys.java
> +public class RequestContextKeys {
Fait

2020-12-03 09:56 UTC, martin-grescu commented on src/test/java/com/payline/payment/amazonv2/MockUtils.java
> +public class MockUtils {
Fait

2020-12-03 10:06 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/utils/PluginUtils.java
> +public class PluginUtils {
Fait

2020-12-03 10:06 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/utils/amazon/ErrorConverter.java
> +public class ErrorConverter {
Fait

2020-12-04 13:55 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/bean/configuration/RequestConfiguration.java
> +    public static RequestConfiguration build(CaptureRequest request) {
Fait

2020-12-04 14:36 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/service/LogoPaymentFormConfigurationService.java
> +    private static final Logger LOGGER = LogManager.getLogger(LogoPaymentFormConfigurationService.class);
Fait

2020-12-04 14:36 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/service/impl/ConfigurationServiceImpl.java
> +public class ConfigurationServiceImpl implements ConfigurationService {
Fait

2020-12-04 14:36 UTC, martin-grescu commented on src/main/java/com/payline/payment/amazonv2/service/impl/PaymentFormConfigurationServiceImpl.java
> +public class PaymentFormConfigurationServiceImpl extends LogoPaymentFormConfigurationService {
Fait

2020-12-14 07:58 UTC, JeremyMattio commented on src/main/java/com/payline/payment/amazonv2/bean/CheckoutSession.java
> +public class CheckoutSession extends AmazonBean {
Il me semble que tu peux supprimer les private également.

2020-12-14 08:15 UTC, JeremyMattio reviewed
Hello,

Voici mes petits retours .

Bien cordialement,

Jérémy Mattio

2020-12-14 08:15 UTC, JeremyMattio commented on src/main/java/com/payline/payment/amazonv2/bean/CheckoutSession.java
> +public class CheckoutSession extends AmazonBean {
Il me semble que tu peux supprimer les private également.

2020-12-14 08:15 UTC, JeremyMattio commented on src/main/java/com/payline/payment/amazonv2/bean/ErrorResponse.java
> +public class ErrorResponse {
Même chose pas besoin du private
@Value is shorthand for: final @ToString @EqualsAndHashCode @AllArgsConstructor @FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE) @Getter

2020-12-14 08:15 UTC, JeremyMattio commented on src/main/java/com/payline/payment/amazonv2/bean/Refund.java
> +public class Refund extends AmazonBean {
Pas de private

2020-12-14 08:15 UTC, JeremyMattio commented on src/main/java/com/payline/payment/amazonv2/bean/Script.java
> +public class Script {
Pareil pour les private. L'objet est immutable aussi donc pas besoin de final selon moi

2020-12-14 08:15 UTC, JeremyMattio commented on src/main/java/com/payline/payment/amazonv2/bean/nested/Address.java
> +public class Address {
On peut supprimer les private

2020-12-14 08:15 UTC, JeremyMattio commented on src/main/java/com/payline/payment/amazonv2/bean/nested/WebCheckoutDetails.java
>      private String checkoutReviewReturnUrl;
private inutile

2020-12-14 08:15 UTC, JeremyMattio commented on src/main/java/com/payline/payment/amazonv2/service/RequestConfigurationService.java
> +        private static final RequestConfigurationService instance = new RequestConfigurationService();
INSTANCE c'est un static final donc majuscule.

2020-12-15 09:35 UTC, merged